name: App Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -R

      - name: Run tests
        run: pytest -q tests
